# Generated by Django 4.2.3 on 2023-07-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_follows'),
        ('posts', '0002_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='Текст уведомления')),
                ('is_view', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Просмотрено')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_me_notifications', to='user_profile.profile', verbose_name='От профиля')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_me_notifications', to='user_profile.profile', verbose_name='Для профиля')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
