# Generated by Django 4.2.3 on 2023-07-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_follows'),
        ('posts', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'post')},
        ),
    ]
