version: "3.9"

services:

  instagram:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/instagram

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5444:5444"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:

