# Generated by Django 4.2.3 on 2023-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_description_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='user_profile.profile', verbose_name='Подписки'),
        ),
    ]
